### PR TITLE
working on #98

### PR DESCRIPTION
**Pull request by ershovd**
- add SignOutUser command, add SignedInEmployee property
- add UI to CheckInPage.xaml to show current sign-in user and a log out
button

Notes:
@j0nscalet  why  `App.Instance.SignOut` doesn't expire session on logout? this is bug or it is by design? I manually reset it at `CheckInViewModel`.`SignOutUser`

### CODE REVIEW

**Comment by ershovd** [comment]
@danielqualitykitchen this is how Check in screen
simulator screen shot 28 2017 15 11 15
 looks right now. Feel free to give some suggestions on what to improve in design part.

**Comment by danielqualitykitchen** [comment]
@ershovd   Great work on this!  I like this very much

@j0nscalet any feedback

**Comment by j0nscalet** [comment]
@danielqualitykitchen @ershovd Did some tweaking... what do you guys think?

@ershovd The reason why `Signout` doesn't expire the user's session is because right now sessions are handled client side not server side. If we expired the user's session they would have to go through the 'Check In' workflow again which is what we're trying by using sessions.

image

**Comment by danielqualitykitchen** [comment]
@ershovd @j0nscalet 

Great job boys!

**Comment by j0nscalet** [comment]
image

My brain was fried so I decided to take out some low hanging fruit. Shift and Station buttons now wrap and layout so much better.

**Comment by danielqualitykitchen** [comment]
@j0nscalet @ershovd   Good job between the both of you.  This looks super nice.  Well done.

**Comment by j0nscalet** [comment]
Thanks @danielqualitykitchen! That was all you @ershovd 👍

**Pull request merged**
