### PR TITLE
When task description is too long a “More” link should be displayed #21

### PR DESCRIPTION
**Pull request by gaoguangli**

### CODE REVIEW

**Comment by j0nscalet** [comment]
@gaoguangli Thanks!

**Comment by j0nscalet** [comment]
@ershovd I put this on ice for now as we need to focus on Sprint 3. Hopefully I'll have some extra time this week to take a look at this.

**Comment by j0nscalet** [comment]
@ershovd let's discuss this tomorrow morning. I think we should be able to write a iOS renderer to dynamically change the height of the `UITableViewCell`. 

What are you thoughts?

**Comment by ershovd** [comment]
@j0nscalet sure, let discuss this issue. and the approach we can try, since this issue is quite nasty as it seems. I will look for options we have

**Pull request closed without merging**
