### PR TITLE
working on #29

### PR DESCRIPTION
**Pull request by ershovd**
- add test image
- add HasIncidents property to Viewmodel
- add Image and IsVisible bindings for IncidentCenterPage.xaml
- add calls for SetHasIncidents whenever Incidents count is changing

### CODE REVIEW

**Comment by j0nscalet** [comment]
A note after review: we should replace the detail `StackLayout` with a `RelativeLayout`. We should put the `ListView` and empty `Image` inside it. Then we can use the `HasIncident` property toggle the visibility of the elements. This way the `Width` and `Height` of each element will `Fill and Expand`.

@ershovd - I know your focused elsewhere, so no need to tackle this right away. (I may be able to circle around and finish it) What are your thoughts on tweaking the approach though?

**Comment by ershovd** [comment]
@j0nscalet this may be a better approach, but I am not sure if we should focus now on XAML performance too much. overall, I guess we should start with profiling/optimizing most critical parts.  https://blog.xamarin.com/optimizing-xamarin-forms-apps-for-maximum-performance/   take a special look at Compiled XAML. the major benefit I guess is that most errors in Xaml layout will be shown in compile-time, not runtime.

**Comment by j0nscalet** [comment]
@ershovd Let's not worry about this now. I simply wanted to get my thoughts down on paper. Thanks!

**Comment by j0nscalet** [comment]
@ershovd I'm taking care of this, I need it for something else I'm working on.

**Comment by j0nscalet** [comment]
@ershovd Take a look at this if you'd like. I made some tweaks to what you had put together as I needed it for something else I was working on.

**Pull request merged**
