### PR TITLE
working on #36

### PR DESCRIPTION
**Pull request by ershovd**
- implement CompleteTaskAsync and HandleFlagTaskCommand in viewmodel
- implement TaskFailedEventArgs events and subcriptions in ViewModels
- implement DisplayAlert in xaml.cs for MainPage and FlagTaskDialog

Things to do:
- implement checking for corresponding exception types
- maybe implement display of alert in single page (MainPage), move Messaging.Subscribe to single page.
- display of alert for diff errors/exception types?

### CODE REVIEW

**Comment by j0nscalet** [comment]
@ershovd I agree I can't think of much benefit to using an event versus catching the exception.

On another note, can you pull from `dev` make sure you're using  the `new` version and re-submit the PR? I'm having trouble looking at the changes because of that.

Thanks!

**Comment by ershovd** [comment]
I've spend on this task additionaly 1h30m, due to the fact that I need to merge with new/ folder version, and previous work is irrelevant. I've updated estimate to match total spent time (1h30m before great refactoring and 1h30 after).

**Comment by j0nscalet** [comment]
@ershovd before moving forward on this, I'd like to discuss your changes.

**Comment by j0nscalet** [comment]
@ershovd functionality looks good. I have some questions about the code which I'll post in the review so look out for those.

**Comment by j0nscalet** [comment]
@ershovd DisplayAlertCommand is getting called n times where n is the # of rows in the ListView.

**Pull request merged**
