### PR TITLE
Refactored #28 to be more extensible

### PR DESCRIPTION
**Pull request by j0nscalet**
First, I changed the underlying HttpServiceClient to point to the API
0.1.1 endpoints. I also skip over the sign in workflow and launch
Incident Center first.

- IncidentCenterPage/IncidentCenterPageViewModel - moved all the logic
I could to the VM so it’s clean, readable, and as testable as possible

- I created CountableMenuItem<TEntity> class
It’s responsible for create menu items from a list of entities
(source), generating a count based on a query. This query can be used
to filter the source as well which avoids duplication.

- FilterIncidents - using the Query property from CountableMenuItem
this filters a local copy Incidents

### CODE REVIEW

**Comment by j0nscalet** [comment]
@ershovd take a look at what I did here. This should give you some clarity from our discussion yesterday.

Based on the responsibilities of `CountableMenuItem<TEntity>`, do you think you we could name it a bit better?

**Comment by j0nscalet** [comment]
I've merged this in to #11  to make dealing with conflicts easier so I'm going to close this.

**Comment by ershovd** [comment]
@j0nscalet I think the `CountableMenuItem` should be named something like FilteredMenuItem, as a main purpose is actually allowing using of `Query` property

**Comment by j0nscalet** [comment]
@ershovd READ MY STINKING MIND 🙌  😀

**Pull request closed without merging**
